artifactoryIntegration: artifactInt

GitRepo:
  name: TestYmlPipeline
  gitProvider: TestInt
  path: akhilesh073/ymlTest
  branches:
    include: master

Image:
  name: myDockerImage
  sourceRepository: mySourceRepo

Pipeline:
  name: myDockerPipeline

DockerBuild:
  name: myDockerBuild
  dockerFileName: Dockerfile
  dockerImageName: testDockerImage

DockerPush:
  targetRepository: docker-local

Bash:
  name: myBashStep
